package boblet;

import java.io.IOException;

import boblet.command.Command;
import boblet.exception.BobletException;
import boblet.util.Parser;
import boblet.util.Storage;
import boblet.util.TaskList;

/**
 * The main class of the Boblet application.
 * Handles the initialization of components and the main program flow.
 */
public class Boblet {
    private Storage storage;
    private TaskList tasks;

    /**
     * Constructs a new Boblet instance and initializes its components.
     *
     * @param filePath The file path to store and load tasks.
     */
    public Boblet(String filePath) {
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.loadTasks());
        } catch (IOException | BobletException e) {
            tasks = new TaskList();
        }
    }

    /**
     * Generates a response for the user's chat message.
     *
     * @param input The user's input command.
     * @return The response generated by executing the command.
     */
    public String getResponse(String input) {
        try {
            Command command = Parser.parse(input); // Parse the command
            return command.execute(tasks, storage); // Execute and return response
        } catch (BobletException e) {
            return e.getMessage(); // Return error message
        }
    }

}
